### ISSUE TITLE
Set up file upload and storage:

### ISSUE THREAD

**Issue by SenpaiSumpie** [QJMTech/TeamBandit#119]
Follow these vidoes, I'd recommend using multer with express to do it.
https://www.youtube.com/watch?v=ysS4sL6lLDU

https://www.youtube.com/watch?v=oeMokkPaL6Y

https://www.youtube.com/watch?v=srPXMt1Q0nY

**Comment by LScholl63** [comment]
Note: express-fileupload was used instead of multer
