### ISSUE TITLE
Course permanently breaks if a schedule is added at all

### ISSUE THREAD

**Issue by BattleDakota** [QJMTech/TeamBandit#181]
If you submit the schedule form before selecting a calendar date, the schedule page becomes unusable and displays an error message; cannot delete course after that.

**Comment by BattleDakota** [comment]
Broke again with one of the recent merges, not sure which but working on this right now

**Comment by LScholl63** [comment]
> Broke again with one of the recent merges, not sure which but working on this right now

I am not sure which PR it came from either, but I have a commit that fixes this, and it will be in my next PR

**Comment by BattleDakota** [comment]
Okay I won't mess with it then

**Comment by BattleDakota** [comment]
> > Broke again with one of the recent merges, not sure which but working on this right now
> 
> I am not sure which PR it came from either, but I have a commit that fixes this, and it will be in my next PR

Got it
